#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"; CACHE_DIR="$DOKKU_ROOT/$APP/cache"

PLUGIN_DIR=$(dirname $0)
. "$PLUGIN_DIR/lib/helpers"

# Check for Procfile
id=$(docker run -d $IMAGE test -f app/Procfile)
if [ $(docker wait $id) -ne 0 ]; then
  echo "Procfile not found"
  exit 0
fi

copy_to_container "$PLUGIN_DIR/lib/task-runner" /usr/local/bin/task-runner

echo "-----> Injecting App Task Runner ..."
DOCKER_ARGS=$(: | pluginhook docker-args $APP)
id=$(docker run -d -v $CACHE_DIR:/cache $DOCKER_ARGS $IMAGE /bin/bash -c "/bin/bash /usr/local/bin/task-runner")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
