#!/bin/bash

set -e
HOME=/app
LOGDIR=/var/log/app
PROCFILE=${HOME}/Procfile
[ ! -d $LOGDIR ] && mkdir -p $LOGDIR
for file in $HOME/.profile.d/*; do source $file; done
hash -r
cd $HOME
cat "$PROCFILE" | while read line; do
  if [ ! -n "$line" ]; then
    continue
  fi
  case "$line" in
    web:*|worker:*|urgentworker:*|clock:*)
      continue
    ;;
    *)
      TASK=${line%%:*}
      echo "      running task ${TASK}"
      CMD=$(ruby -e "require 'yaml';puts YAML.load_file('Procfile')['${TASK}']")
      echo $CMD | bash -e | tee -a ${LOGDIR}/${TASK}-runner.log
      if [ "$?" -ne 0 ];then
        echo "${TASK} failed. aborting..."
        exit $?
      fi
      ;;
  esac
done
