#!/bin/bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
HOME=/app
PROCFILE=${HOME}/Procfile
SCALEFILE=${HOME}/SCALE

for file in $HOME/.profile.d/*; do source $file; done
hash -r
echo "restoring installation cache..."
rm -rf /tmp/cache || true
ln -sf /cache /tmp/cache || true
cd $HOME
while read line || [[ -n "$line" ]]; do
  [[ -z "$line" ]] && continue
  TASK=${line%%:*}
  if [[ -f "$SCALEFILE" ]]; then
    SCALE=$(egrep "^$TASK=" "$SCALEFILE" || true)
    if [[ -z "$SCALE" ]]; then
      continue
    fi
    NUM_PROCS=${SCALE#*=}
    if [[ "$NUM_PROCS" -eq 0 ]]; then
      echo "=====> running task ${TASK}"
      CMD=$(ruby -e "require 'yaml';puts YAML.load_file('Procfile')['${TASK}']")
      echo $CMD | bash -e
      if [[ "$?" -ne 0 ]];then
        echo "${TASK} failed. aborting..."
        exit $?
      fi
    fi
  else
    case "$line" in
      web:*|worker:*|urgentworker:*|clock:*)
        continue
        ;;
    esac
  fi
done < "$PROCFILE"
echo "removing installation cache..."
rm -f /tmp/cache || true
